### ISSUE TITLE
No matching distribution found for urllib

### ISSUE THREAD

**Issue by brandontict** [ThomasTJdev/python_gdork_sqli#1]
Couldn't find answer via google, so I was hoping you can shed some light on this issue. 
```

 python_gdork_sqli git:(master) pip3 install psutil bs4 requests urllib
Collecting psutil
  Using cached psutil-5.0.1.tar.gz
Requirement already satisfied: bs4 in /root/.local/lib/python3.5/site-packages/bs4-0.0.1-py3.5.egg
Requirement already satisfied: requests in /usr/lib/python3/dist-packages
Collecting urllib
  Could not find a version that satisfies the requirement urllib (from versions: )
No matching distribution found for urllib

``` 

First time I've encountered issues with pip or pip3 . 

Of course when attempting to run the script I receive errors due to no module 
```
➜  python_gdork_sqli git:(master) python3 findsqlinj.py 
Traceback (most recent call last):
  File "findsqlinj.py", line 19, in <module>
    import psutil                       # Checking possible VPN connection
ImportError: No module named 'psutil'
```

Thanks for your work and sharing this project~!

**Comment by ThomasTJdev** [comment]
Hi @brandontict !

Thank you trying out the code!

### urllib
Pip (pip3) can not install urllib since it is a standard library. 
To test if it's installed, you should open a python console and write the following without error messages: `import urllib`. If you get an error message, you have to install the standard library.   
**Arch:** `sudo pacman -S python-urllib3` (with python3 as standard)   
**Ubuntu:** `apt-get install python3-urllib3`

### Error
Your error is not related to the urllib library, it is related to the library psutil. Please try to install psutil again with `pip3 install psutil`.   
After the installation, you should open a python console and write the following without error messages: `import psutil`.

**Comment by brandontict** [comment]
Thanks for your fast response .  

apt-get install python3-urllib3 seem to do the trick, 

When I was troubleshooting I looked via apt-cache search and did not come up with urllib3 for some odd reason... 

Keep up the great work! and once again thank you for sharing :+1:
